In [1]:
import pandas as pd

In [2]:
weather=pd.read_csv("weather_data.csv")

In [4]:
weather

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017          NaN        9.0   Sunny
2   1/5/2017         28.0        NaN    Snow
3   1/6/2017          NaN        7.0     NaN
4   1/7/2017         32.0        NaN    Rain
5   1/8/2017          NaN        NaN   Sunny
6   1/9/2017          NaN        NaN     NaN
7  1/10/2017         34.1        8.1  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [5]:
weather["temperature"].median()

32.0

In [7]:
weather["temperature"]=weather["temperature"].fillna(weather["temperature"].median())

In [8]:
weather # updated df after missing value handled

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017         32.0        9.0   Sunny
2   1/5/2017         28.0        NaN    Snow
3   1/6/2017         32.0        7.0     NaN
4   1/7/2017         32.0        NaN    Rain
5   1/8/2017         32.0        NaN   Sunny
6   1/9/2017         32.0        NaN     NaN
7  1/10/2017         34.1        8.1  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [10]:
weather['comment'] = weather['temperature'].apply(lambda x: 'hot' if x > 30 else 'cool')

In [11]:
weather

         day  temperature  windspeed   event comment
0   1/1/2017         32.0        6.0    Rain     hot
1   1/4/2017         32.0        9.0   Sunny     hot
2   1/5/2017         28.0        NaN    Snow    cool
3   1/6/2017         32.0        7.0     NaN     hot
4   1/7/2017         32.0        NaN    Rain     hot
5   1/8/2017         32.0        NaN   Sunny     hot
6   1/9/2017         32.0        NaN     NaN     hot
7  1/10/2017         34.1        8.1  Cloudy     hot
8  1/11/2017         40.0       12.0   Sunny     hot